<!DOCTYPE html>
<html>
	<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Error</title>
    <link rel="stylesheet" type="text/css" href="/webjars/bootstrap/css/bootstrap.min.css" /> 
  	</head>
	<body>
		<div class="text-center">
			<h1>Access Denied!</h1>
			<h1>Make sure your subscription is active</h1>				
		</div>
	</body>
</html>