
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>To Note application</title>

	<link rel="stylesheet" type="text/css" href="/webjars/bootstrap/css/bootstrap.min.css" />

	<meta name="theme-color" content="#563d7c">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="/css/application.css" rel="stylesheet">
  </head>
  <body>
  
<!--     <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom box-shadow">
      <h5 class="my-0 mr-md-auto font-weight-normal"><img class="mb-2" src="/images/tonote1.png" alt="" width="200"></h5>
      <a class="btn btn-outline-primary" href="/">Log out</a>
    </div> -->

<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
          	<h5 class="pt-3 pb-3 my-0 mr-md-auto font-weight-normal"><img class="mb-2" src="/images/tonote1.png" alt="" width="200"></h5>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="#">
              Notes
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              User profile
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              Billings
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              Users
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              New list
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 p-0">
    
      <div class="p-4 d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Notes</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
			<a class="btn btn-outline-primary" href="/">Log out</a>
        </div>
      </div>
      
      <div class="float-right pr-4">
	      <button type="button" class="btn btn-sm btn-outline-secondary">
	            New
	      </button>
      </div>
          
      <div class="table-responsive p-4">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>Note content</th>
              <th>Checked</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</td>
              <td><input type="checkbox"></td>
              <td>delete edit</td>
            </tr>
            <tr>
              <td>second item</td>
              <td><input type="checkbox"></td>
              <td>delete edit</td>
            </tr>
            <tr>
              <td>third item</td>
              <td><input type="checkbox"></td>
              <td>delete edit</td>
            </tr>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="/webjars/jquery/jquery-slim.min.js"><\/script>')</script>
    
    <script type="text/javascript" src="/webjars/holderjs/holder.min.js"></script>
    <script type="text/javascript" src="/webjars/jquery/jquery.min.js"></script>
	<script type="text/javascript" src="/webjars/bootstrap/js/bootstrap.min.js"></script>
</html>
