<!doctype html>
<html lang="en">
  <head>
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	    <meta name="description" content="">
	    <meta name="author" content="">
	
	    <title>ToNote</title>
	    <link rel="stylesheet" type="text/css" href="/webjars/bootstrap/css/bootstrap.min.css" />
	    <!-- Custom styles for this template -->
	    <link href="/css/login.css" rel="stylesheet">
  	</head>
	<body class="text-center">
	  
	<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
	<img class="mb-4" src="/images/logo.png" alt="" width="70">   
      <h1 class="display-4">To Note</h1>
      <p class="lead">Please login to continue</p>
	  <a class="btn btn-lg  btn-primary" href="/oauth2/authorization/unity">Login</a>
	  <p class="mt-5 mb-3 text-muted">&copy; 2020</p>
     </div>
	</body>
  </html>