<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ToNote</title>
    <link rel="stylesheet" type="text/css" href="/webjars/bootstrap/css/bootstrap.min.css" />
  	</head>
	<body>
	
	<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">To Note</h1>
      <p class="lead">Please login to continue</p>
	  <a class="btn btn-lg  btn-primary" href="/oauth2/authorization/unity">Login</a>
     </div>
	</body>
  </html>